# Generated by Django 4.0.6 on 2024-04-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0002_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(to='LEI.linguagemdeprogramacao'),
        ),
    ]
