# Generated by Django 4.0.6 on 2024-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0004_alter_projeto_disciplina_alter_projeto_linguagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ects',
            field=models.CharField(max_length=100),
        ),
    ]
