# Generated by Django 4.0.6 on 2024-04-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0005_alter_disciplina_ano_alter_disciplina_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LEI.curso'),
        ),
    ]
