# Generated by Django 4.0.6 on 2024-04-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0006_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='LEI.disciplina'),
        ),
    ]
