# Generated by Django 4.0.6 on 2024-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0008_remove_projeto_disciplina_projeto_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
