# Generated by Django 4.0.6 on 2024-05-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0009_projeto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='projetos',
            field=models.ManyToManyField(to='LEI.projeto'),
        ),
    ]
