# Generated by Django 4.0.6 on 2024-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEI', '0010_remove_projeto_disciplina_disciplina_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='imagem',
            field=models.ImageField(null=True, upload_to='projetos'),
        ),
    ]
