# Generated by Django 4.0.6 on 2024-03-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albuns',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='musicas',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='albuns',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='bandas',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='link',
        ),
        migrations.AddField(
            model_name='albuns',
            name='ano_lancamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bandas',
            name='ano_criacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bandas',
            name='nacionalidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='musicas',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.albuns'),
        ),
        migrations.AddField(
            model_name='musicas',
            name='duracao',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='albuns',
            name='banda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.bandas'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='banda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.bandas'),
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField(default=0)),
                ('banda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.bandas')),
            ],
        ),
    ]
