# Generated by Django 4.0.6 on 2024-03-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_rename_nome_albuns_titulo_rename_nome_musicas_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicas',
            name='disco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.discos'),
        ),
    ]
