# Generated by Django 4.0.6 on 2024-03-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_musicas_disco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicas',
            name='disco',
        ),
        migrations.DeleteModel(
            name='Discos',
        ),
    ]
