# Generated by Django 4.0.6 on 2024-04-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_remove_musicas_disco_delete_discos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicas',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.albuns'),
        ),
    ]
