# Generated by Django 4.0.6 on 2024-05-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_alter_musicas_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandas',
            name='imagem',
            field=models.ImageField(default='bandas/default.jpg', null=True, upload_to='bandas/'),
        ),
        migrations.AddField(
            model_name='musicas',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='musicas',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
