# Generated by Django 4.0.6 on 2024-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_bandas_imagem_musicas_biografia_musicas_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicas',
            name='biografia',
        ),
        migrations.AddField(
            model_name='bandas',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
