# Generated by Django 4.0.6 on 2024-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_bandas_descricaocompleta_bandas_imagemintegrantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuns',
            name='imagem',
            field=models.ImageField(default='bandas/default.jpg', null=True, upload_to='bandas/'),
        ),
        migrations.AddField(
            model_name='albuns',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='musicas',
            name='imagem',
            field=models.ImageField(default='bandas/default.jpg', null=True, upload_to='bandas/'),
        ),
        migrations.AddField(
            model_name='musicas',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
