# Generated by Django 4.0.6 on 2024-04-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(default='', max_length=100)),
                ('ano_criacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='festivaiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_criacao', models.IntegerField(default=0)),
                ('imagem', models.ImageField(null=True, upload_to='festivais')),
                ('bandas', models.ManyToManyField(to='festivalappcertaparaoteste.band')),
                ('localizacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festivalappcertaparaoteste.localizacao')),
            ],
        ),
    ]
